services:
  - type: web
    name: the-world-of-brainrots
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: World_of_Brianrots   # Указываем папку, где лежит ваш сервер
    envVars:
      - key: SESSION_SECRET
        value: brainrot-ultimate-secret-key
      - key: PORT
        value: 3000